name: Lone Star Press
favicon: null
layout_spectrum: 0.94828
typography_spectrum: 0.5
title: The new home of Lone Star Press
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#95b1ea'
    - '#7a7a7a'
    - '#c6c6c6'
    - '#4e5c7a'
  brandStrength: 0.4221207273658365
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
