name: Lone Star Press
favicon: null
layout_spectrum: 0.4327688361518085
typography_spectrum: 0.5
title: The new home of Lone Star Press
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4221207273658365
  lightness: 0.6502332936506718
  saturation: 0.6385285200085491
  rhythmicContrast: 0.8442361510824412
purpose: []
